In [ ]:
# Задание 1
Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [15]:
import numpy as np

my_array = np.arange(5, 101, 5)


print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [3]:
# Задание 2
Из полученного массива получить массив с кратными 10 числами

SyntaxError: invalid syntax (325506405.py, line 2)

In [26]:
filtered_array = my_array[my_array % 10 == 0]

print(filtered_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# Задание 3
Получить двумерный массив с двумя столбцами

In [27]:
two_column_array = filtered_array.reshape(-1, 2)

print(two_column_array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [ ]:
# Задание 4
Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [28]:
two_column_array_second = two_column_array - 5

print(two_column_array_second)

[[ 5 15]
 [25 35]
 [45 55]
 [65 75]
 [85 95]]


In [ ]:
# Задание 5
Соедините массивы two_column_array (из задания 3) и my_second_array (из задания 4), горизонтально. Используйте .T для транспонирования матрицы.

In [32]:
joined_array = np.hstack((two_column_array, two_column_array_second))

print(joined_array)

[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]]


In [ ]:
# Задание 6
Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [36]:
#division_2nd_row = np.array([joined_array[1] / joined_array[i] for i in range(4)])

#division_3rd_row = np.array([joined_array[2] / joined_array[i] for i in range(4)])
division_2nd_row = joined_array[1] / joined_array[3]
#print(division_2nd_row)

division_3rd_row = joined_array[2] / joined_array[3]

#print(joined_array)
new_joined_array = joined_array.copy().astype(float)
new_joined_array[1] = division_2nd_row
new_joined_array[2] = division_3rd_row

print(new_joined_array)

[[ 10.          20.           5.          15.        ]
 [  0.42857143   0.5          0.38461538   0.46666667]
 [  0.71428571   0.75         0.69230769   0.73333333]
 [ 70.          80.          65.          75.        ]
 [ 90.         100.          85.          95.        ]]


In [ ]:
# Задание 7
Оставить только те значения, которые не изменились после деления

In [38]:
rows_equal = np.all(joined_array == new_joined_array, axis=1)

# Оставляем только совпадающие строки
leftover = new_joined_array[rows_equal]

print(leftover)

[[ 10.  20.   5.  15.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


In [ ]:
# Задание 8
Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [39]:
leftover[[0, 2]] = leftover[[2, 0]]
print(leftover)

[[ 90. 100.  85.  95.]
 [ 70.  80.  65.  75.]
 [ 10.  20.   5.  15.]]


In [ ]:
# Задание 9
Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [40]:
mean_values = np.mean(leftover, axis=1)

median_values = np.median(leftover, axis=1)

std_values = np.std(leftover, axis=1)

print("Mean:", mean_values)
print("Median:", median_values)
print("STD:", std_values)

Mean: [92.5 72.5 12.5]
Median: [92.5 72.5 12.5]
STD: [5.59016994 5.59016994 5.59016994]


In [ ]:
# Задание 10
Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

In [42]:
max_values = np.max(leftover, axis=1, keepdims=True)

normalized_result = leftover / max_values

print(normalized_result)

[[0.9    1.     0.85   0.95  ]
 [0.875  1.     0.8125 0.9375]
 [0.5    1.     0.25   0.75  ]]
