In [ ]:
# Задание 1
Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [2]:
import numpy as np

my_array = np.arange(5, 101, 5)


print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [3]:
# Задание 2
Из полученного массива получить массив с кратными 10 числами

SyntaxError: invalid syntax (325506405.py, line 2)

In [4]:
filtered_array = my_array[my_array % 10 == 0]

print(filtered_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# Задание 3
Получить двумерный массив с двумя столбцами

In [5]:
two_column_array = filtered_array.reshape(-1, 2)

print(two_column_array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [ ]:
# Задание 4
Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [6]:
my_second_array = my_array - 5

print(my_second_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
# Задание 5
Соедините массивы two_column_array (из задания 3) и my_second_array (из задания 4), горизонтально. Используйте .T для транспонирования матрицы.

In [23]:
#transposed_array = two_column_array.T

#print (two_column_array)

#print ( my_second_array)
my_second_array_reshaped = my_second_array.reshape(-1, 4)
my_second_array_reshaped_transposed = my_second_array_reshaped.T
#print (my_second_array_reshaped)

result = np.hstack((two_column_array, my_second_array_reshaped))

print(result)

[[ 10  20   0   5  10  15]
 [ 30  40  20  25  30  35]
 [ 50  60  40  45  50  55]
 [ 70  80  60  65  70  75]
 [ 90 100  80  85  90  95]]


In [ ]:
# Задание 6
Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [24]:
rows_2_and_3 = result[1:3] 

first_4_rows = my_array[:4]

division_result = rows_2_and_3 / first_4_rows[:2]

transposed_result = division_result.T

print(transposed_result)

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [9]:
result_after_mask = transposed_result[transposed_result == 1]

print(result_after_mask)

[]
