In [ ]:
# Задание 1
Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [3]:
import numpy as np

my_array = np.arange(5, 101, 5)


print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [3]:
# Задание 2
Из полученного массива получить массив с кратными 10 числами

SyntaxError: invalid syntax (325506405.py, line 2)

In [4]:
filtered_array = my_array[my_array % 10 == 0]

print(filtered_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# Задание 3
Получить двумерный массив с двумя столбцами

In [5]:
two_column_array = filtered_array.reshape(-1, 2)

print(two_column_array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [ ]:
# Задание 4
Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [6]:
two_column_array_second = two_column_array - 5

print(two_column_array_second)

[[ 5 15]
 [25 35]
 [45 55]
 [65 75]
 [85 95]]


In [ ]:
# Задание 5
Соедините массивы two_column_array (из задания 3) и my_second_array (из задания 4), горизонтально. Используйте .T для транспонирования матрицы.

In [10]:
joined_array = np.hstack((two_column_array, two_column_array_second))

print(joined_array)

[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]]


In [ ]:
# Задание 6
Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [12]:
division_2nd_row = np.array([joined_array[1] / joined_array[i] for i in range(4)])

division_3rd_row = np.array([joined_array[2] / joined_array[i] for i in range(4)])

print(division_2nd_row)

print(division_3rd_row)

[[3.         2.         5.         2.33333333]
 [1.         1.         1.         1.        ]
 [0.6        0.66666667 0.55555556 0.63636364]
 [0.42857143 0.5        0.38461538 0.46666667]]
[[5.         3.         9.         3.66666667]
 [1.66666667 1.5        1.8        1.57142857]
 [1.         1.         1.         1.        ]
 [0.71428571 0.75       0.69230769 0.73333333]]


In [ ]:
# Задание 7
Оставить только те значения, которые не изменились после деления

[]
